version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001" # Use a different port for the backend to avoid conflict with react-app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - Recipes_db:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: recipe-application
    working_dir: /app
    depends_on:
      - backend
    volumes:
      - ./react-app:/app      # Mount the app source code
      - /app/node_modules     # Ensure container's node_modules is not overwritten
    ports:
      - "3000:3000"

volumes:
  Recipes_db:
